AWSTemplateFormatVersion: "2010-09-09"
Resources:
  mostViewedTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "date"
          AttributeType: "S"
        -
          AttributeName: "rank"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "date"
          KeyType: "HASH"
        -
          AttributeName: "rank"
          KeyType: "RANGE"
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      TableName: MostViewedArticles
