services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: wof
      MYSQL_PASSWORD: wof
      MYSQL_ROOT_PASSWORD: wof
    ports:
      - '3306:3306'
    expose:
      - '3306'
  nginx:
    image: nginx:stable
    restart: always
    ports:
      - '80:80'
    expose:
      - '80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
