name: Deploy AWS Lambda processing the data from the DynamoDB table

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - amazon-architecture/lambdas/process-dynamo-views/**

jobs:
  lambda:
    name: Build and publish nginx container
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: amazon-architecture/lambdas/process-dynamo-views
    steps:
      - uses: actions/checkout@v2
      - name: Install Node version 14 compatible with AWS runtime
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1
      - run: npm install
      - run: zip -r function.zip .
      - run: aws lambda update-function-code --function-name processDynamoViewsLambda --zip-file fileb://function.zip
