name: Seed DynamoDB tables

on:
  workflow_dispatch:

jobs:
  viewsTable:
    name: Seed the most viewed articles table.
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: wikimedia-requests
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm ci
      - run: node seedMostViewedArticlesTable.js
