name: Update the `processDynamoViewsLambda` AWS Lambda function

on:
  push:
    branches:
      - main
    paths:
      - "amazon-architecture/lambdas/process-dynamo-views/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: amazon-architecture/lambdas/process-dynamo-views
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: eu-central-1

      - name: Zip the directory contents and update the lambda including the environmental variables
        env:
          LAMBDA: processDynamoViewsLambda
        run: |
          zip -r function.zip .
          aws lambda update-function-code \
            --function-name ${{LAMBDA}} \
            --zip-file fileb://function.zip
          aws lambda function-updated --function-name ${{LAMBDA}}
          aws lambda update-function-configuration \
            --function-name ${{LAMBDA}} \
            --environment "Variables={DB_HOST=${{secrets.DB_HOST}},DB_USER=${{secrets.DB_USER}},DB_PASS=${{secrets.DB_PASS}},DB_SCHEMA=${{secrets.DB_SCHEMA}}}"

